### PR TITLE
relax hardcoded check in d5a adapter

### PR DESCRIPTION
**Pull request by peendebak**

### CODE REVIEW

**Comment by bogdanvconstantin** [comment]
Hi Pieter,

Can you please let me know why the 4v bi was left there as well as the 2v bi? From what I understood today in your slides we only have one voltage (2v bi?). Thank you!

**Comment by peendebak** [comment]
> Hi @eendebakpt,
> 
> Can you please let me know why the 4v bi was left there as well as the 2v bi? From what I understood today in your slides we only have one voltage (2v bi?). Thank you!

This was a quick fix to get the system working. A proper solution for remove the constraints here and put them in a system dependent setting (and rethink the whole concept of the adapters). @bogdanvconstantin

**Comment by bogdanvconstantin** [comment]
Ok, Thank you! can you please add me and one more to the reviewers of the PR? (Olaf/Fer?)

**Comment by oschusler** [comment]
@peendebak could you please explain to me what this 2v bi (and 4v bi) do? I essence, the Python code looks good, but I just don't know what you did, and since this is an opensource library, I would like to know what it means.

**Comment by peendebak** [comment]
> @peendebak could you please explain to me what this 2v bi (and 4v bi) do? I essence, the Python code looks good, but I just don't know what you did, and since this is an opensource library, I would like to know what it means.

The DAC can output in a range of -2 V to + 2 V (4v bi = range 4V bidirectional), or in -1 V to +1 V (2b bi) or in a range from 0V to 4V (4v uni = 4 volt unidirectional)

**Review by oschusler — APPROVED** [review]
Purely based on the code, I approve. However, I don't know if this fits the design.

**Review by bogdanvconstantin — APPROVED** [review]
👍

**Pull request merged**
